import { ProfileData } from "../types/auth";

export const userFormData: ProfileData = {
  display_name: "",
  username: "",
  gender: "",
  income: "",
  education: "",
  ethnicity: "",
  marital_status: "",
  birth_date: "",
  country: "",
  city: "",
  state: "",
  employment_status: "",
  occupation: "",
  fav_sport: "",
  hobbies: "",
  fav_music: "",
  dietary_pref: "",
  physical_level: "",
  fav_book: "",
  social_media_usage: "",
  fav_movie: "",
  travel_freq: "",
  pet_ownership: "",
  bio: "",
  is_private_votes: false,
  is_private_polls: false,
  cover_image: "",
  profile_photo: "",
};
